services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "ubuntus"
      RAM_SIZE: "5G"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/sdc:/disk2
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
